---

- hosts: all-nodes
  roles:
    - k8s-common

- hosts: kube-master
  vars_files: 
    - vars.yml
  roles:
    - k8s-master

- hosts: kube-nodes
  vars_files: 
    - vars.yml
  roles:
    - k8s-nodes
