---

- name:           rm -rf /var/lib/apt/lists/partial
  become:         true
  file:
    path:         /var/lib/apt/lists/partial
    state:        absent

- name:           apt-get update
  become:         true
  shell:          apt-get update -o Acquire::CompressionTypes::Order::=gz
    
- name:           apt-get install -y apt-transport-https
  become:         true
  apt:
    name:         apt-transport-https
    state:        present

- name:           Add APT Key for Kubernetes
  become:         true
  apt_key:
    url:          "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state:        "present"

- name:           Add Repo
  become:         true
  apt_repository:
    repo:         "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state:        "present"

- name:           Apt Get Update
  become:         true
  apt:
    update_cache: "yes"

- name:           Install packages
  become:         true
  apt:
    name:         "{{ item }}"
    state:        "present"
  with_items:
    - docker.io
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni

- name:      Overide Kubelet service config to add IP Address
  become:    true
  template:
    src:     "10-kubeadm.conf"
    dest:    "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
  notify:
    - reload systemd

- meta: flush_handlers
